/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { JsonApiLink } from './json-api-link';

/**
 * 
 * @export
 * @interface AdminEntryPointResponseLinks
 */
export interface AdminEntryPointResponseLinks {
    /**
     * 
     * @type {JsonApiLink}
     * @memberof AdminEntryPointResponseLinks
     */
    'self': JsonApiLink;
    /**
     * 
     * @type {JsonApiLink}
     * @memberof AdminEntryPointResponseLinks
     */
    'clockifyHook': JsonApiLink;
    /**
     * 
     * @type {JsonApiLink}
     * @memberof AdminEntryPointResponseLinks
     */
    'clockifyService': JsonApiLink;
    /**
     * 
     * @type {JsonApiLink}
     * @memberof AdminEntryPointResponseLinks
     */
    'clockifySettings': JsonApiLink;
    /**
     * 
     * @type {JsonApiLink}
     * @memberof AdminEntryPointResponseLinks
     */
    'clockifyUser': JsonApiLink;
    /**
     * 
     * @type {JsonApiLink}
     * @memberof AdminEntryPointResponseLinks
     */
    'mocoHook': JsonApiLink;
    /**
     * 
     * @type {JsonApiLink}
     * @memberof AdminEntryPointResponseLinks
     */
    'mocoService': JsonApiLink;
    /**
     * 
     * @type {JsonApiLink}
     * @memberof AdminEntryPointResponseLinks
     */
    'mocoSettings': JsonApiLink;
    /**
     * 
     * @type {JsonApiLink}
     * @memberof AdminEntryPointResponseLinks
     */
    'organization': JsonApiLink;
    /**
     * 
     * @type {JsonApiLink}
     * @memberof AdminEntryPointResponseLinks
     */
    'user': JsonApiLink;
}

