/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClockifySettingsAttributes } from './clockify-settings-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifySettingsUpdateRequestRelationships } from './clockify-settings-update-request-relationships';

/**
 * 
 * @export
 * @interface ClockifySettingsUpdateRequestData
 */
export interface ClockifySettingsUpdateRequestData {
    /**
     * Resource type
     * @type {string}
     * @memberof ClockifySettingsUpdateRequestData
     */
    'type': ClockifySettingsUpdateRequestDataTypeEnum;
    /**
     * 
     * @type {ClockifySettingsAttributes}
     * @memberof ClockifySettingsUpdateRequestData
     */
    'attributes': ClockifySettingsAttributes;
    /**
     * 
     * @type {ClockifySettingsUpdateRequestRelationships}
     * @memberof ClockifySettingsUpdateRequestData
     */
    'relationships': ClockifySettingsUpdateRequestRelationships;
}

export const ClockifySettingsUpdateRequestDataTypeEnum = {
    ClockifySettings: 'ClockifySettings'
} as const;

export type ClockifySettingsUpdateRequestDataTypeEnum = typeof ClockifySettingsUpdateRequestDataTypeEnum[keyof typeof ClockifySettingsUpdateRequestDataTypeEnum];


