/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClockifySettingsAttributes } from './clockify-settings-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifySettingsCreateRequestRelationships } from './clockify-settings-create-request-relationships';

/**
 * 
 * @export
 * @interface ClockifySettingsCreateRequestData
 */
export interface ClockifySettingsCreateRequestData {
    /**
     * Resource type
     * @type {string}
     * @memberof ClockifySettingsCreateRequestData
     */
    'type': ClockifySettingsCreateRequestDataTypeEnum;
    /**
     * 
     * @type {ClockifySettingsAttributes}
     * @memberof ClockifySettingsCreateRequestData
     */
    'attributes': ClockifySettingsAttributes;
    /**
     * 
     * @type {ClockifySettingsCreateRequestRelationships}
     * @memberof ClockifySettingsCreateRequestData
     */
    'relationships': ClockifySettingsCreateRequestRelationships;
}

export const ClockifySettingsCreateRequestDataTypeEnum = {
    ClockifySettings: 'ClockifySettings'
} as const;

export type ClockifySettingsCreateRequestDataTypeEnum = typeof ClockifySettingsCreateRequestDataTypeEnum[keyof typeof ClockifySettingsCreateRequestDataTypeEnum];


