/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClockifyUserAttributes } from './clockify-user-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifyUserRelationships } from './clockify-user-relationships';

/**
 * The Clockify User Resource.
 * @export
 * @interface ClockifyUserResource
 */
export interface ClockifyUserResource {
    /**
     * Resource identifier
     * @type {string}
     * @memberof ClockifyUserResource
     */
    'id': string;
    /**
     * Resource type
     * @type {string}
     * @memberof ClockifyUserResource
     */
    'type': ClockifyUserResourceTypeEnum;
    /**
     * 
     * @type {ClockifyUserAttributes}
     * @memberof ClockifyUserResource
     */
    'attributes': ClockifyUserAttributes;
    /**
     * 
     * @type {ClockifyUserRelationships}
     * @memberof ClockifyUserResource
     */
    'relationships': ClockifyUserRelationships;
}

export const ClockifyUserResourceTypeEnum = {
    ClockifyUser: 'ClockifyUser'
} as const;

export type ClockifyUserResourceTypeEnum = typeof ClockifyUserResourceTypeEnum[keyof typeof ClockifyUserResourceTypeEnum];


