/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.1.0+e417cb8
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClockifyServiceAttributes } from './clockify-service-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifyServiceUpdateRequestRelationships } from './clockify-service-update-request-relationships';

/**
 * 
 * @export
 * @interface ClockifyServiceUpdateRequestData
 */
export interface ClockifyServiceUpdateRequestData {
    /**
     * Resource type
     * @type {string}
     * @memberof ClockifyServiceUpdateRequestData
     */
    'type': ClockifyServiceUpdateRequestDataTypeEnum;
    /**
     * 
     * @type {ClockifyServiceAttributes}
     * @memberof ClockifyServiceUpdateRequestData
     */
    'attributes': ClockifyServiceAttributes;
    /**
     * 
     * @type {ClockifyServiceUpdateRequestRelationships}
     * @memberof ClockifyServiceUpdateRequestData
     */
    'relationships': ClockifyServiceUpdateRequestRelationships;
}

export const ClockifyServiceUpdateRequestDataTypeEnum = {
    ClockifyService: 'ClockifyService'
} as const;

export type ClockifyServiceUpdateRequestDataTypeEnum = typeof ClockifyServiceUpdateRequestDataTypeEnum[keyof typeof ClockifyServiceUpdateRequestDataTypeEnum];


