/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.1.0+e417cb8
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClockifyHookAttributes } from './clockify-hook-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifyHookLinks } from './clockify-hook-links';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifyHookRelationships } from './clockify-hook-relationships';

/**
 * The Clockify Hook Resource.
 * @export
 * @interface ClockifyHookResource
 */
export interface ClockifyHookResource {
    /**
     * Resource identifier
     * @type {string}
     * @memberof ClockifyHookResource
     */
    'id': string;
    /**
     * Resource type
     * @type {string}
     * @memberof ClockifyHookResource
     */
    'type': ClockifyHookResourceTypeEnum;
    /**
     * 
     * @type {ClockifyHookAttributes}
     * @memberof ClockifyHookResource
     */
    'attributes': ClockifyHookAttributes;
    /**
     * 
     * @type {ClockifyHookLinks}
     * @memberof ClockifyHookResource
     */
    'links'?: ClockifyHookLinks;
    /**
     * 
     * @type {ClockifyHookRelationships}
     * @memberof ClockifyHookResource
     */
    'relationships': ClockifyHookRelationships;
}

export const ClockifyHookResourceTypeEnum = {
    ClockifyHook: 'ClockifyHook'
} as const;

export type ClockifyHookResourceTypeEnum = typeof ClockifyHookResourceTypeEnum[keyof typeof ClockifyHookResourceTypeEnum];


