/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClockifyUserResource } from './clockify-user-resource';
// May contain unused imports in some cases
// @ts-ignore
import { UserResource } from './user-resource';

/**
 * 
 * @export
 * @interface ClockifyUserResponse
 */
export interface ClockifyUserResponse {
    /**
     * 
     * @type {ClockifyUserResource}
     * @memberof ClockifyUserResponse
     */
    'data': ClockifyUserResource;
    /**
     * 
     * @type {Set<UserResource>}
     * @memberof ClockifyUserResponse
     */
    'included'?: Set<UserResource>;
}

