/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClockifySettingsCollectionResponseLinks } from './clockify-settings-collection-response-links';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifySettingsCollectionResponseMeta } from './clockify-settings-collection-response-meta';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifySettingsResource } from './clockify-settings-resource';
// May contain unused imports in some cases
// @ts-ignore
import { OrganizationResource } from './organization-resource';

/**
 * 
 * @export
 * @interface ClockifySettingsCollectionResponse
 */
export interface ClockifySettingsCollectionResponse {
    /**
     * 
     * @type {ClockifySettingsCollectionResponseLinks}
     * @memberof ClockifySettingsCollectionResponse
     */
    'links': ClockifySettingsCollectionResponseLinks;
    /**
     * 
     * @type {ClockifySettingsCollectionResponseMeta}
     * @memberof ClockifySettingsCollectionResponse
     */
    'meta': ClockifySettingsCollectionResponseMeta;
    /**
     * 
     * @type {Set<ClockifySettingsResource>}
     * @memberof ClockifySettingsCollectionResponse
     */
    'data': Set<ClockifySettingsResource>;
    /**
     * 
     * @type {Set<OrganizationResource>}
     * @memberof ClockifySettingsCollectionResponse
     */
    'included'?: Set<OrganizationResource>;
}

