/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClockifyHookAttributes } from './clockify-hook-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifyHookUpdateRequestRelationships } from './clockify-hook-update-request-relationships';

/**
 * 
 * @export
 * @interface ClockifyHookUpdateRequestData
 */
export interface ClockifyHookUpdateRequestData {
    /**
     * Resource type
     * @type {string}
     * @memberof ClockifyHookUpdateRequestData
     */
    'type': ClockifyHookUpdateRequestDataTypeEnum;
    /**
     * 
     * @type {ClockifyHookAttributes}
     * @memberof ClockifyHookUpdateRequestData
     */
    'attributes': ClockifyHookAttributes;
    /**
     * 
     * @type {ClockifyHookUpdateRequestRelationships}
     * @memberof ClockifyHookUpdateRequestData
     */
    'relationships': ClockifyHookUpdateRequestRelationships;
}

export const ClockifyHookUpdateRequestDataTypeEnum = {
    ClockifyHook: 'ClockifyHook'
} as const;

export type ClockifyHookUpdateRequestDataTypeEnum = typeof ClockifyHookUpdateRequestDataTypeEnum[keyof typeof ClockifyHookUpdateRequestDataTypeEnum];


