/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The Clockify Settings Attributes.
 * @export
 * @interface ClockifySettingsAttributes
 */
export interface ClockifySettingsAttributes {
    /**
     * Clockify settings identifier
     * @type {string}
     * @memberof ClockifySettingsAttributes
     */
    '_id'?: string;
    /**
     * Clockify workspace ID
     * @type {string}
     * @memberof ClockifySettingsAttributes
     */
    'workspaceId': string;
}

