/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClockifyHookCollectionResponseIncludedInner } from './clockify-hook-collection-response-included-inner';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifyHookResource } from './clockify-hook-resource';

/**
 * 
 * @export
 * @interface ClockifyHookResponse
 */
export interface ClockifyHookResponse {
    /**
     * 
     * @type {ClockifyHookResource}
     * @memberof ClockifyHookResponse
     */
    'data': ClockifyHookResource;
    /**
     * 
     * @type {Set<ClockifyHookCollectionResponseIncludedInner>}
     * @memberof ClockifyHookResponse
     */
    'included'?: Set<ClockifyHookCollectionResponseIncludedInner>;
}

