/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClockifyServiceAttributes } from './clockify-service-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifyServiceCreateRequestRelationships } from './clockify-service-create-request-relationships';

/**
 * 
 * @export
 * @interface ClockifyServiceCreateRequestData
 */
export interface ClockifyServiceCreateRequestData {
    /**
     * Resource type
     * @type {string}
     * @memberof ClockifyServiceCreateRequestData
     */
    'type': ClockifyServiceCreateRequestDataTypeEnum;
    /**
     * 
     * @type {ClockifyServiceAttributes}
     * @memberof ClockifyServiceCreateRequestData
     */
    'attributes': ClockifyServiceAttributes;
    /**
     * 
     * @type {ClockifyServiceCreateRequestRelationships}
     * @memberof ClockifyServiceCreateRequestData
     */
    'relationships': ClockifyServiceCreateRequestRelationships;
}

export const ClockifyServiceCreateRequestDataTypeEnum = {
    ClockifyService: 'ClockifyService'
} as const;

export type ClockifyServiceCreateRequestDataTypeEnum = typeof ClockifyServiceCreateRequestDataTypeEnum[keyof typeof ClockifyServiceCreateRequestDataTypeEnum];


