/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.1.0+e417cb8
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClockifyHookAttributes } from './clockify-hook-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifyHookCreateRequestRelationships } from './clockify-hook-create-request-relationships';

/**
 * 
 * @export
 * @interface ClockifyHookCreateRequestData
 */
export interface ClockifyHookCreateRequestData {
    /**
     * Resource type
     * @type {string}
     * @memberof ClockifyHookCreateRequestData
     */
    'type': ClockifyHookCreateRequestDataTypeEnum;
    /**
     * 
     * @type {ClockifyHookAttributes}
     * @memberof ClockifyHookCreateRequestData
     */
    'attributes': ClockifyHookAttributes;
    /**
     * 
     * @type {ClockifyHookCreateRequestRelationships}
     * @memberof ClockifyHookCreateRequestData
     */
    'relationships': ClockifyHookCreateRequestRelationships;
}

export const ClockifyHookCreateRequestDataTypeEnum = {
    ClockifyHook: 'ClockifyHook'
} as const;

export type ClockifyHookCreateRequestDataTypeEnum = typeof ClockifyHookCreateRequestDataTypeEnum[keyof typeof ClockifyHookCreateRequestDataTypeEnum];


