/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClockifySettingsAttributes } from './clockify-settings-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifySettingsRelationships } from './clockify-settings-relationships';

/**
 * The Clockify Settings Resource.
 * @export
 * @interface ClockifySettingsResource
 */
export interface ClockifySettingsResource {
    /**
     * Resource identifier
     * @type {string}
     * @memberof ClockifySettingsResource
     */
    'id': string;
    /**
     * Resource type
     * @type {string}
     * @memberof ClockifySettingsResource
     */
    'type': ClockifySettingsResourceTypeEnum;
    /**
     * 
     * @type {ClockifySettingsAttributes}
     * @memberof ClockifySettingsResource
     */
    'attributes': ClockifySettingsAttributes;
    /**
     * 
     * @type {ClockifySettingsRelationships}
     * @memberof ClockifySettingsResource
     */
    'relationships': ClockifySettingsRelationships;
}

export const ClockifySettingsResourceTypeEnum = {
    ClockifySettings: 'ClockifySettings'
} as const;

export type ClockifySettingsResourceTypeEnum = typeof ClockifySettingsResourceTypeEnum[keyof typeof ClockifySettingsResourceTypeEnum];


