/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClockifyHookCollectionResponseIncludedInner } from './clockify-hook-collection-response-included-inner';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifyHookCollectionResponseLinks } from './clockify-hook-collection-response-links';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifyHookCollectionResponseMeta } from './clockify-hook-collection-response-meta';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifyHookResource } from './clockify-hook-resource';

/**
 * 
 * @export
 * @interface ClockifyHookCollectionResponse
 */
export interface ClockifyHookCollectionResponse {
    /**
     * 
     * @type {ClockifyHookCollectionResponseLinks}
     * @memberof ClockifyHookCollectionResponse
     */
    'links': ClockifyHookCollectionResponseLinks;
    /**
     * 
     * @type {ClockifyHookCollectionResponseMeta}
     * @memberof ClockifyHookCollectionResponse
     */
    'meta': ClockifyHookCollectionResponseMeta;
    /**
     * 
     * @type {Set<ClockifyHookResource>}
     * @memberof ClockifyHookCollectionResponse
     */
    'data': Set<ClockifyHookResource>;
    /**
     * 
     * @type {Set<ClockifyHookCollectionResponseIncludedInner>}
     * @memberof ClockifyHookCollectionResponse
     */
    'included'?: Set<ClockifyHookCollectionResponseIncludedInner>;
}

