/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClockifyHookCreateRequestRelationshipsUser } from './clockify-hook-create-request-relationships-user';
// May contain unused imports in some cases
// @ts-ignore
import { OrganizationRelationship } from './organization-relationship';

/**
 * 
 * @export
 * @interface ClockifyHookCreateRequestRelationships
 */
export interface ClockifyHookCreateRequestRelationships {
    /**
     * 
     * @type {OrganizationRelationship}
     * @memberof ClockifyHookCreateRequestRelationships
     */
    'organization': OrganizationRelationship;
    /**
     * 
     * @type {ClockifyHookCreateRequestRelationshipsUser}
     * @memberof ClockifyHookCreateRequestRelationships
     */
    'user'?: ClockifyHookCreateRequestRelationshipsUser;
}

