/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClockifyWebhookRequestProject } from './clockify-webhook-request-project';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifyWebhookRequestTag } from './clockify-webhook-request-tag';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifyWebhookRequestTask } from './clockify-webhook-request-task';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifyWebhookRequestTimeInterval } from './clockify-webhook-request-time-interval';
// May contain unused imports in some cases
// @ts-ignore
import { ClockifyWebhookRequestUser } from './clockify-webhook-request-user';

/**
 * 
 * @export
 * @interface ClockifyWebhookRequest
 */
export interface ClockifyWebhookRequest {
    /**
     * 
     * @type {string}
     * @memberof ClockifyWebhookRequest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ClockifyWebhookRequest
     */
    'description': string;
    /**
     * 
     * @type {ClockifyWebhookRequestTimeInterval}
     * @memberof ClockifyWebhookRequest
     */
    'timeInterval': ClockifyWebhookRequestTimeInterval;
    /**
     * 
     * @type {Array<ClockifyWebhookRequestTag>}
     * @memberof ClockifyWebhookRequest
     */
    'tags': Array<ClockifyWebhookRequestTag>;
    /**
     * 
     * @type {ClockifyWebhookRequestProject}
     * @memberof ClockifyWebhookRequest
     */
    'project'?: ClockifyWebhookRequestProject;
    /**
     * 
     * @type {ClockifyWebhookRequestTask}
     * @memberof ClockifyWebhookRequest
     */
    'task'?: ClockifyWebhookRequestTask;
    /**
     * 
     * @type {ClockifyWebhookRequestUser}
     * @memberof ClockifyWebhookRequest
     */
    'user': ClockifyWebhookRequestUser;
}

