/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { JsonApiErrorItemSource } from './json-api-error-item-source';
// May contain unused imports in some cases
// @ts-ignore
import { JsonApiLink } from './json-api-link';

/**
 * 
 * @export
 * @interface JsonApiErrorItem
 */
export interface JsonApiErrorItem {
    /**
     * A unique identifier for this particular occurence of the problem.
     * @type {string}
     * @memberof JsonApiErrorItem
     */
    'id'?: string;
    /**
     * 
     * @type {{ [key: string]: JsonApiLink; }}
     * @memberof JsonApiErrorItem
     */
    'links'?: { [key: string]: JsonApiLink; };
    /**
     * The HTTP status code applicable to this problem, expressed as a string value.
     * @type {string}
     * @memberof JsonApiErrorItem
     */
    'status'?: string;
    /**
     * An application-specific error code, expressed as a string value.
     * @type {string}
     * @memberof JsonApiErrorItem
     */
    'code'?: string;
    /**
     * A short human-readable summary of the problem. It **SHOULD NOT** change from occurence to occurence of the problem, except for purposes of localization.
     * @type {string}
     * @memberof JsonApiErrorItem
     */
    'title'?: string;
    /**
     * A human-readable explanation specific to this occurence of the problem.
     * @type {string}
     * @memberof JsonApiErrorItem
     */
    'detail'?: string;
    /**
     * 
     * @type {JsonApiErrorItemSource}
     * @memberof JsonApiErrorItem
     */
    'source'?: JsonApiErrorItemSource;
    /**
     * A meta object containing non-standard meta-information about the error.
     * @type {object}
     * @memberof JsonApiErrorItem
     */
    'meta'?: object;
}

