/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.1.0+e417cb8
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MocoHookAttributes } from './moco-hook-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { MocoHookLinks } from './moco-hook-links';
// May contain unused imports in some cases
// @ts-ignore
import { MocoHookRelationships } from './moco-hook-relationships';

/**
 * The MOCO Hook Resource.
 * @export
 * @interface MocoHookResource
 */
export interface MocoHookResource {
    /**
     * Resource identifier
     * @type {string}
     * @memberof MocoHookResource
     */
    'id': string;
    /**
     * Resource type
     * @type {string}
     * @memberof MocoHookResource
     */
    'type': MocoHookResourceTypeEnum;
    /**
     * 
     * @type {MocoHookAttributes}
     * @memberof MocoHookResource
     */
    'attributes': MocoHookAttributes;
    /**
     * 
     * @type {MocoHookLinks}
     * @memberof MocoHookResource
     */
    'links'?: MocoHookLinks;
    /**
     * 
     * @type {MocoHookRelationships}
     * @memberof MocoHookResource
     */
    'relationships': MocoHookRelationships;
}

export const MocoHookResourceTypeEnum = {
    MocoHook: 'MocoHook'
} as const;

export type MocoHookResourceTypeEnum = typeof MocoHookResourceTypeEnum[keyof typeof MocoHookResourceTypeEnum];


