/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.1.0+e417cb8
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MocoSettingsRelationships } from './moco-settings-relationships';
// May contain unused imports in some cases
// @ts-ignore
import { MocoSettingsResource } from './moco-settings-resource';
// May contain unused imports in some cases
// @ts-ignore
import { UserAttributes } from './user-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { UserResource } from './user-resource';

/**
 * @type MocoServiceCollectionResponseIncludedInner
 * @export
 */
export type MocoServiceCollectionResponseIncludedInner = MocoSettingsResource | UserResource;


