/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MOCOCompanyWebhookRequest } from './mococompany-webhook-request';
// May contain unused imports in some cases
// @ts-ignore
import { MOCOProjectWebhookRequest } from './mocoproject-webhook-request';
// May contain unused imports in some cases
// @ts-ignore
import { MOCOProjectWebhookRequestContract } from './mocoproject-webhook-request-contract';
// May contain unused imports in some cases
// @ts-ignore
import { MOCOProjectWebhookRequestCustomer } from './mocoproject-webhook-request-customer';
// May contain unused imports in some cases
// @ts-ignore
import { MOCOTaskWebhookRequest } from './mocotask-webhook-request';
// May contain unused imports in some cases
// @ts-ignore
import { MOCOTaskWebhookRequestProject } from './mocotask-webhook-request-project';
// May contain unused imports in some cases
// @ts-ignore
import { MOCOUserWebhookRequest } from './mocouser-webhook-request';

/**
 * @type MOCOWebhookRequest
 * @export
 */
export type MOCOWebhookRequest = MOCOCompanyWebhookRequest | MOCOProjectWebhookRequest | MOCOTaskWebhookRequest | MOCOUserWebhookRequest;


