/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MocoHookAttributes } from './moco-hook-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { MocoHookCreateRequestRelationships } from './moco-hook-create-request-relationships';

/**
 * 
 * @export
 * @interface MocoHookCreateRequestData
 */
export interface MocoHookCreateRequestData {
    /**
     * Resource type
     * @type {string}
     * @memberof MocoHookCreateRequestData
     */
    'type': MocoHookCreateRequestDataTypeEnum;
    /**
     * 
     * @type {MocoHookAttributes}
     * @memberof MocoHookCreateRequestData
     */
    'attributes': MocoHookAttributes;
    /**
     * 
     * @type {MocoHookCreateRequestRelationships}
     * @memberof MocoHookCreateRequestData
     */
    'relationships': MocoHookCreateRequestRelationships;
}

export const MocoHookCreateRequestDataTypeEnum = {
    MocoHook: 'MocoHook'
} as const;

export type MocoHookCreateRequestDataTypeEnum = typeof MocoHookCreateRequestDataTypeEnum[keyof typeof MocoHookCreateRequestDataTypeEnum];


