/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * User Request Object
 * @export
 * @interface MOCOUserWebhookRequest
 */
export interface MOCOUserWebhookRequest {
    /**
     * 
     * @type {number}
     * @memberof MOCOUserWebhookRequest
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof MOCOUserWebhookRequest
     */
    'firstname': string;
    /**
     * 
     * @type {string}
     * @memberof MOCOUserWebhookRequest
     */
    'lastname': string;
    /**
     * 
     * @type {string}
     * @memberof MOCOUserWebhookRequest
     */
    'email': string;
}

