/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The MOCO Hook Attributes.
 * @export
 * @interface MocoHookAttributes
 */
export interface MocoHookAttributes {
    /**
     * MOCO hook identifier
     * @type {string}
     * @memberof MocoHookAttributes
     */
    '_id'?: string;
    /**
     * Clockify hook status
     * @type {string}
     * @memberof MocoHookAttributes
     */
    'status': MocoHookAttributesStatusEnum;
    /**
     * Clockify signature
     * @type {string}
     * @memberof MocoHookAttributes
     */
    'signatureKey': string;
    /**
     * 
     * @type {string}
     * @memberof MocoHookAttributes
     */
    'event': MocoHookAttributesEventEnum;
    /**
     * 
     * @type {string}
     * @memberof MocoHookAttributes
     */
    'target': MocoHookAttributesTargetEnum;
}

export const MocoHookAttributesStatusEnum = {
    Enabled: 'ENABLED',
    Disabled: 'DISABLED'
} as const;

export type MocoHookAttributesStatusEnum = typeof MocoHookAttributesStatusEnum[keyof typeof MocoHookAttributesStatusEnum];
export const MocoHookAttributesEventEnum = {
    Created: 'CREATED',
    Updated: 'UPDATED',
    Deleted: 'DELETED',
    Archived: 'ARCHIVED'
} as const;

export type MocoHookAttributesEventEnum = typeof MocoHookAttributesEventEnum[keyof typeof MocoHookAttributesEventEnum];
export const MocoHookAttributesTargetEnum = {
    Company: 'COMPANY',
    Project: 'PROJECT',
    Task: 'TASK',
    User: 'USER'
} as const;

export type MocoHookAttributesTargetEnum = typeof MocoHookAttributesTargetEnum[keyof typeof MocoHookAttributesTargetEnum];


