/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MocoSettingsAttributes } from './moco-settings-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { MocoSettingsRelationships } from './moco-settings-relationships';

/**
 * The MOCO Settings Resource.
 * @export
 * @interface MocoSettingsResource
 */
export interface MocoSettingsResource {
    /**
     * Resource identifier
     * @type {string}
     * @memberof MocoSettingsResource
     */
    'id': string;
    /**
     * Resource type
     * @type {string}
     * @memberof MocoSettingsResource
     */
    'type': MocoSettingsResourceTypeEnum;
    /**
     * 
     * @type {MocoSettingsAttributes}
     * @memberof MocoSettingsResource
     */
    'attributes': MocoSettingsAttributes;
    /**
     * 
     * @type {MocoSettingsRelationships}
     * @memberof MocoSettingsResource
     */
    'relationships': MocoSettingsRelationships;
}

export const MocoSettingsResourceTypeEnum = {
    MocoSettings: 'MocoSettings'
} as const;

export type MocoSettingsResourceTypeEnum = typeof MocoSettingsResourceTypeEnum[keyof typeof MocoSettingsResourceTypeEnum];


