/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.1.0+e417cb8
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MocoServiceAttributes } from './moco-service-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { MocoServiceUpdateRequestRelationships } from './moco-service-update-request-relationships';

/**
 * 
 * @export
 * @interface MocoServiceUpdateRequestData
 */
export interface MocoServiceUpdateRequestData {
    /**
     * Resource type
     * @type {string}
     * @memberof MocoServiceUpdateRequestData
     */
    'type': MocoServiceUpdateRequestDataTypeEnum;
    /**
     * 
     * @type {MocoServiceAttributes}
     * @memberof MocoServiceUpdateRequestData
     */
    'attributes': MocoServiceAttributes;
    /**
     * 
     * @type {MocoServiceUpdateRequestRelationships}
     * @memberof MocoServiceUpdateRequestData
     */
    'relationships': MocoServiceUpdateRequestRelationships;
}

export const MocoServiceUpdateRequestDataTypeEnum = {
    MocoService: 'MocoService'
} as const;

export type MocoServiceUpdateRequestDataTypeEnum = typeof MocoServiceUpdateRequestDataTypeEnum[keyof typeof MocoServiceUpdateRequestDataTypeEnum];


