/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The MOCO Service Attributes.
 * @export
 * @interface MocoServiceAttributes
 */
export interface MocoServiceAttributes {
    /**
     * MOCO service identifier
     * @type {string}
     * @memberof MocoServiceAttributes
     */
    '_id'?: string;
    /**
     * MOCO service status
     * @type {string}
     * @memberof MocoServiceAttributes
     */
    'status': MocoServiceAttributesStatusEnum;
    /**
     * MOCO API key
     * @type {string}
     * @memberof MocoServiceAttributes
     */
    'apiKey': string;
}

export const MocoServiceAttributesStatusEnum = {
    Enabled: 'ENABLED',
    Disabled: 'DISABLED'
} as const;

export type MocoServiceAttributesStatusEnum = typeof MocoServiceAttributesStatusEnum[keyof typeof MocoServiceAttributesStatusEnum];


