/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MocoServiceCollectionResponseIncludedInner } from './moco-service-collection-response-included-inner';
// May contain unused imports in some cases
// @ts-ignore
import { MocoServiceCollectionResponseLinks } from './moco-service-collection-response-links';
// May contain unused imports in some cases
// @ts-ignore
import { MocoServiceCollectionResponseMeta } from './moco-service-collection-response-meta';
// May contain unused imports in some cases
// @ts-ignore
import { MocoServiceResource } from './moco-service-resource';

/**
 * 
 * @export
 * @interface MocoServiceCollectionResponse
 */
export interface MocoServiceCollectionResponse {
    /**
     * 
     * @type {MocoServiceCollectionResponseLinks}
     * @memberof MocoServiceCollectionResponse
     */
    'links': MocoServiceCollectionResponseLinks;
    /**
     * 
     * @type {MocoServiceCollectionResponseMeta}
     * @memberof MocoServiceCollectionResponse
     */
    'meta': MocoServiceCollectionResponseMeta;
    /**
     * 
     * @type {Set<MocoServiceResource>}
     * @memberof MocoServiceCollectionResponse
     */
    'data': Set<MocoServiceResource>;
    /**
     * 
     * @type {Set<MocoServiceCollectionResponseIncludedInner>}
     * @memberof MocoServiceCollectionResponse
     */
    'included'?: Set<MocoServiceCollectionResponseIncludedInner>;
}

