/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.1.0+e417cb8
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MocoSettingsAttributes } from './moco-settings-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { MocoSettingsCreateRequestRelationships } from './moco-settings-create-request-relationships';

/**
 * 
 * @export
 * @interface MocoSettingsCreateRequestData
 */
export interface MocoSettingsCreateRequestData {
    /**
     * Resource type
     * @type {string}
     * @memberof MocoSettingsCreateRequestData
     */
    'type': MocoSettingsCreateRequestDataTypeEnum;
    /**
     * 
     * @type {MocoSettingsAttributes}
     * @memberof MocoSettingsCreateRequestData
     */
    'attributes': MocoSettingsAttributes;
    /**
     * 
     * @type {MocoSettingsCreateRequestRelationships}
     * @memberof MocoSettingsCreateRequestData
     */
    'relationships': MocoSettingsCreateRequestRelationships;
}

export const MocoSettingsCreateRequestDataTypeEnum = {
    MocoSettings: 'MocoSettings'
} as const;

export type MocoSettingsCreateRequestDataTypeEnum = typeof MocoSettingsCreateRequestDataTypeEnum[keyof typeof MocoSettingsCreateRequestDataTypeEnum];


