/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The MOCO Settings Attributes.
 * @export
 * @interface MocoSettingsAttributes
 */
export interface MocoSettingsAttributes {
    /**
     * MOCO service identifier
     * @type {string}
     * @memberof MocoSettingsAttributes
     */
    '_id'?: string;
    /**
     * MOCO API host
     * @type {string}
     * @memberof MocoSettingsAttributes
     */
    'host': string;
}

