/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.1.0+e417cb8
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MocoSettingsRelationshipData } from './moco-settings-relationship-data';

/**
 * The MOCO Settings Relationship.
 * @export
 * @interface MocoSettingsRelationship
 */
export interface MocoSettingsRelationship {
    /**
     * 
     * @type {MocoSettingsRelationshipData}
     * @memberof MocoSettingsRelationship
     */
    'data': MocoSettingsRelationshipData;
}

