/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MOCOTaskWebhookRequestProject } from './mocotask-webhook-request-project';

/**
 * Task Request Object
 * @export
 * @interface MOCOTaskWebhookRequest
 */
export interface MOCOTaskWebhookRequest {
    /**
     * 
     * @type {number}
     * @memberof MOCOTaskWebhookRequest
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof MOCOTaskWebhookRequest
     */
    'name': string;
    /**
     * 
     * @type {MOCOTaskWebhookRequestProject}
     * @memberof MOCOTaskWebhookRequest
     */
    'project': MOCOTaskWebhookRequestProject;
}

