/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrganizationRelationshipData
 */
export interface OrganizationRelationshipData {
    /**
     * Resource identifier
     * @type {string}
     * @memberof OrganizationRelationshipData
     */
    'id': string;
    /**
     * Resource type
     * @type {string}
     * @memberof OrganizationRelationshipData
     */
    'type': OrganizationRelationshipDataTypeEnum;
}

export const OrganizationRelationshipDataTypeEnum = {
    Organization: 'Organization'
} as const;

export type OrganizationRelationshipDataTypeEnum = typeof OrganizationRelationshipDataTypeEnum[keyof typeof OrganizationRelationshipDataTypeEnum];


