/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.1.0+e417cb8
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OrganizationAttributes } from './organization-attributes';

/**
 * The Organization Resource.
 * @export
 * @interface OrganizationResource
 */
export interface OrganizationResource {
    /**
     * Resource identifier
     * @type {string}
     * @memberof OrganizationResource
     */
    'id': string;
    /**
     * Resource type
     * @type {string}
     * @memberof OrganizationResource
     */
    'type': OrganizationResourceTypeEnum;
    /**
     * 
     * @type {OrganizationAttributes}
     * @memberof OrganizationResource
     */
    'attributes': OrganizationAttributes;
}

export const OrganizationResourceTypeEnum = {
    Organization: 'Organization'
} as const;

export type OrganizationResourceTypeEnum = typeof OrganizationResourceTypeEnum[keyof typeof OrganizationResourceTypeEnum];


