/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.1.0+e417cb8
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Metadata related to pagination
 * @export
 * @interface PaginationMetadata
 */
export interface PaginationMetadata {
    /**
     * Amount of elements in total
     * @type {number}
     * @memberof PaginationMetadata
     */
    'totalItems': number;
    /**
     * Amount of elements per page
     * @type {number}
     * @memberof PaginationMetadata
     */
    'itemsPerPage': number;
    /**
     * Number of the current page
     * @type {number}
     * @memberof PaginationMetadata
     */
    'currentPage': number;
}

