/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.1.0+e417cb8
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserCollectionResponseLinks } from './user-collection-response-links';
// May contain unused imports in some cases
// @ts-ignore
import { UserCollectionResponseMeta } from './user-collection-response-meta';
// May contain unused imports in some cases
// @ts-ignore
import { UserResource } from './user-resource';

/**
 * 
 * @export
 * @interface UserCollectionResponse
 */
export interface UserCollectionResponse {
    /**
     * 
     * @type {UserCollectionResponseLinks}
     * @memberof UserCollectionResponse
     */
    'links': UserCollectionResponseLinks;
    /**
     * 
     * @type {UserCollectionResponseMeta}
     * @memberof UserCollectionResponse
     */
    'meta': UserCollectionResponseMeta;
    /**
     * 
     * @type {Set<UserResource>}
     * @memberof UserCollectionResponse
     */
    'data': Set<UserResource>;
}

