/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.1.0+e417cb8
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The User Attributes.
 * @export
 * @interface UserAttributes
 */
export interface UserAttributes {
    /**
     * User identifier
     * @type {string}
     * @memberof UserAttributes
     */
    '_id'?: string;
    /**
     * Given name
     * @type {string}
     * @memberof UserAttributes
     */
    'givenName': string;
    /**
     * Family name
     * @type {string}
     * @memberof UserAttributes
     */
    'familyName': string;
    /**
     * Email address
     * @type {string}
     * @memberof UserAttributes
     */
    'email': string;
}

