/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.1.0+e417cb8
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserAttributes } from './user-attributes';

/**
 * The User Resource.
 * @export
 * @interface UserResource
 */
export interface UserResource {
    /**
     * Resource identifier
     * @type {string}
     * @memberof UserResource
     */
    'id': string;
    /**
     * Resource type
     * @type {string}
     * @memberof UserResource
     */
    'type': UserResourceTypeEnum;
    /**
     * 
     * @type {UserAttributes}
     * @memberof UserResource
     */
    'attributes': UserAttributes;
}

export const UserResourceTypeEnum = {
    User: 'User'
} as const;

export type UserResourceTypeEnum = typeof UserResourceTypeEnum[keyof typeof UserResourceTypeEnum];


