/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserRelationshipData
 */
export interface UserRelationshipData {
    /**
     * Resource identifier
     * @type {string}
     * @memberof UserRelationshipData
     */
    'id': string;
    /**
     * Resource type
     * @type {string}
     * @memberof UserRelationshipData
     */
    'type': UserRelationshipDataTypeEnum;
}

export const UserRelationshipDataTypeEnum = {
    User: 'User'
} as const;

export type UserRelationshipDataTypeEnum = typeof UserRelationshipDataTypeEnum[keyof typeof UserRelationshipDataTypeEnum];


