/* tslint:disable */
/* eslint-disable */
/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AdminEntryPointResponse } from '../model';
/**
 * AdminApi - axios parameter creator
 * @export
 */
export const AdminApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the RESTful Entry Point Response from the admin API.  This entry point of the API gives information about the supported version of JSON:API, as well as the current app release, and the app version. Furthermore, all important links of the resources of the admin API are listed.
         * @summary Retrieve Admin Entry Point
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdminEntryPoint: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminApi - functional programming interface
 * @export
 */
export const AdminApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves the RESTful Entry Point Response from the admin API.  This entry point of the API gives information about the supported version of JSON:API, as well as the current app release, and the app version. Furthermore, all important links of the resources of the admin API are listed.
         * @summary Retrieve Admin Entry Point
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAdminEntryPoint(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminEntryPointResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAdminEntryPoint(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AdminApi - factory interface
 * @export
 */
export const AdminApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminApiFp(configuration)
    return {
        /**
         * Retrieves the RESTful Entry Point Response from the admin API.  This entry point of the API gives information about the supported version of JSON:API, as well as the current app release, and the app version. Furthermore, all important links of the resources of the admin API are listed.
         * @summary Retrieve Admin Entry Point
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdminEntryPoint(options?: AxiosRequestConfig): AxiosPromise<AdminEntryPointResponse> {
            return localVarFp.getAdminEntryPoint(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminApi - object-oriented interface
 * @export
 * @class AdminApi
 * @extends {BaseAPI}
 */
export class AdminApi extends BaseAPI {
    /**
     * Retrieves the RESTful Entry Point Response from the admin API.  This entry point of the API gives information about the supported version of JSON:API, as well as the current app release, and the app version. Furthermore, all important links of the resources of the admin API are listed.
     * @summary Retrieve Admin Entry Point
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApi
     */
    public getAdminEntryPoint(options?: AxiosRequestConfig) {
        return AdminApiFp(this.configuration).getAdminEntryPoint(options).then((request) => request(this.axios, this.basePath));
    }
}
